import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getProjectMetrics } from "../lib/project-metrics";
import { listProjectManifests, requireProject } from "../lib/projects";
import { SITE } from "../lib/site";
import type { ExternalReview } from "../lib/types";

// Derives every number from the project data and impact files. Anything not
// measured is written as "Not yet measured". No promotional wording is generated.
const manifests = listProjectManifests();
const projects = manifests.map((manifest) => requireProject(manifest.slug));
const perProjectMetrics = projects.map((project) => ({
  project,
  metrics: getProjectMetrics(project),
}));

const totals = perProjectMetrics.reduce(
  (sum, { metrics }) => ({
    people: sum.people + metrics.people,
    places: sum.places + metrics.places,
    sources: sum.sources + metrics.sources,
    relationships: sum.relationships + metrics.relationships,
    mentions: sum.mentions + metrics.mentions,
    mappablePlaces: sum.mappablePlaces + metrics.mappablePlaces,
  }),
  { people: 0, places: 0, sources: 0, relationships: 0, mentions: 0, mappablePlaces: 0 }
);

const impact = JSON.parse(readFileSync(resolve("data/project-impact.json"), "utf8")) as {
  educators_contacted: number;
  classrooms_using: number;
  community_contributors: number;
  presentations: number;
};
const reviews = JSON.parse(readFileSync(resolve("data/external-reviews.json"), "utf8")) as ExternalReview[];

const today = new Date().toISOString().slice(0, 10);
const deploymentUrl = SITE.siteUrl ?? "Not yet measured";

const lines: string[] = [
  "# Application metrics",
  "",
  "This file is generated by `npm run metrics:generate`. Do not edit it by hand. Counts come from the data in `data/` and from the impact records. Values that have not been measured are shown as Not yet measured.",
  "",
  "## TECHNICAL SCOPE",
  "",
  `Projects published: ${manifests.length}`,
  `Canonical people: ${totals.people}`,
  `Places: ${totals.places}`,
  `Sources: ${totals.sources}`,
  `Relationships: ${totals.relationships}`,
  `Archival mentions: ${totals.mentions}`,
  `Georeferenced places: ${totals.mappablePlaces}`,
  `Open-source repository: ${SITE.repoUrl}`,
  "",
];

for (const { project, metrics } of perProjectMetrics) {
  const label =
    project.manifest.status === "pilot"
      ? `${project.manifest.title} (pilot case study)`
      : project.manifest.title;
  lines.push(
    `${label}: ${metrics.people} people / ${metrics.places} places / ${metrics.sources} sources`
  );
}

lines.push(
  "",
  "## EXTERNAL VALIDATION",
  "",
  `External reviews: ${reviews.length}`,
  `Educators contacted: ${impact.educators_contacted}`,
  `Classrooms using: ${impact.classrooms_using}`,
  `Community contributors: ${impact.community_contributors}`,
  `Presentations: ${impact.presentations}`,
  "",
  "## STATUS",
  "",
  `Deployment URL: ${deploymentUrl}`,
  `Last validated: ${today}`,
  ""
);

const output = lines.join("\n");
writeFileSync(resolve("docs/application-metrics.md"), output);

console.log("ARKIVE APPLICATION METRICS");
console.log("==========================");
console.log(output.split("\n").slice(4).join("\n"));
console.log("Written to docs/application-metrics.md");
