import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getProjectMetrics } from "../lib/project-metrics";
import { SITE } from "../lib/site";
import type { ExternalReview } from "../lib/types";

// Derives every number from the project data and impact files. Anything not
// measured is written as "Not yet measured". No promotional wording is generated.
const metrics = getProjectMetrics();
const impact = JSON.parse(readFileSync(resolve("data/project-impact.json"), "utf8")) as {
  educators_contacted: number;
  classrooms_using: number;
  community_contributors: number;
  presentations: number;
};
const reviews = JSON.parse(readFileSync(resolve("data/external-reviews.json"), "utf8")) as ExternalReview[];

const today = new Date().toISOString().slice(0, 10);
const deploymentUrl = SITE.siteUrl ?? "Not yet measured";

const lines = [
  "# Application metrics",
  "",
  "This file is generated by `npm run metrics:generate`. Do not edit it by hand. Counts come from the data in `data/` and from the impact records. Values that have not been measured are shown as Not yet measured.",
  "",
  "## TECHNICAL SCOPE",
  "",
  `Canonical people: ${metrics.people}`,
  `Places: ${metrics.places}`,
  `Sources: ${metrics.sources}`,
  `Relationships: ${metrics.relationships}`,
  `Archival mentions: ${metrics.mentions}`,
  `Georeferenced places: ${metrics.mappablePlaces} (exact ${metrics.exactPlaces}, approximate ${metrics.approximatePlaces})`,
  `Open-source repository: ${SITE.repoUrl}`,
  "",
  "## EXTERNAL VALIDATION",
  "",
  `External reviews: ${reviews.length}`,
  `Educators contacted: ${impact.educators_contacted}`,
  `Classrooms using: ${impact.classrooms_using}`,
  `Community contributors: ${impact.community_contributors}`,
  `Presentations: ${impact.presentations}`,
  "",
  "## STATUS",
  "",
  `Deployment URL: ${deploymentUrl}`,
  `Last validated: ${today}`,
  "",
];

const output = lines.join("\n");
writeFileSync(resolve("docs/application-metrics.md"), output);

console.log("ARKIVE APPLICATION METRICS");
console.log("==========================");
console.log(output.split("\n").slice(4).join("\n"));
console.log("Written to docs/application-metrics.md");
